Unlike the a priori method, the ECLAT method is not based on the calculation of confidence and lift, therefore the ECLAT method is based on the calculation of the support conjunctions of the variables

https://pypi.org/project/pyECLAT/

In [1]:
import pandas as pd
import ast

In [2]:
dataset = pd.read_csv("Retail_Transactions_Dataset.csv")

dataset.head()

,Transaction_ID,Date,Customer_Name,Product,Total_Items,Total_Cost,Payment_Method,City,Store_Type,Discount_Applied,Customer_Category,Season,Promotion
0,1000000000,2022-01-21 06:27:29,Stacey Price,"['Ketchup', 'Shaving Cream', 'Light Bulbs']",3,71.65,Mobile Payment,Los Angeles,Warehouse Club,True,Homemaker,Winter,NaN
1,1000000001,2023-03-01 13:01:21,Michelle Carlson,"['Ice Cream', 'Milk', 'Olive Oil', 'Bread', 'P...",2,25.93,Cash,San Francisco,Specialty Store,True,Professional,Fall,BOGO (Buy One Get One)
2,1000000002,2024-03-21 15:37:04,Lisa Graves,['Spinach'],6,41.49,Credit Card,Houston,Department Store,True,Professional,Winter,NaN
3,1000000003,2020-10-31 09:59:47,Mrs. Patricia May,"['Tissues', 'Mustard']",1,39.34,Mobile Payment,Chicago,Pharmacy,True,Homemaker,Spring,NaN
4,1000000004,2020-12-10 00:59:59,Susan Mitchell,['Dish Soap'],10,16.42,Debit Card,Houston,Specialty Store,False,Young Adult,Winter,Discount on Selected Items

In [3]:
product_list = dataset["Product"].apply(ast.literal_eval).tolist()

products_dataframe = pd.DataFrame(product_list)

products_dataframe

                 0              1              2        3          4
0          Ketchup  Shaving Cream    Light Bulbs      NaN        NaN
1        Ice Cream           Milk      Olive Oil    Bread   Potatoes
2          Spinach            NaN            NaN      NaN        NaN
3          Tissues        Mustard            NaN      NaN        NaN
4        Dish Soap            NaN            NaN      NaN        NaN
...            ...            ...            ...      ...        ...
999995     Pickles        Carrots  Peanut Butter  Sponges  BBQ Sauce
999996      Cereal            NaN            NaN      NaN        NaN
999997  Trash Bags            NaN            NaN      NaN        NaN
999998     Diapers         Coffee         Coffee      Mop        NaN
999999  Trash Cans            Mop            Jam      NaN        NaN

[1000000 rows x 5 columns]

In [4]:
from pyECLAT import ECLAT

eclat_instance = ECLAT(data=products_dataframe,
                       verbose=True)  #verbose=True to see the loading bar

100%|██████████| 81/81 [00:48<00:00,  1.68it/s]
100%|██████████| 81/81 [00:01<00:00, 46.25it/s]
100%|██████████| 81/81 [00:00<00:00, 264.02it/s]

In [5]:
eclat_instance.df_bin  #generate a binary dataframe, that can be used for other analyzes.
eclat_instance.uniq_  #a list with all the names of the different items

['Carrots',
 'Diapers',
 'Plant Fertilizer',
 'Toilet Paper',
 'Pancake Mix',
 'Extension Cords',
 'Shower Gel',
 'Trash Cans',
 'Baby Wipes',
 'Banana',
 'Dish Soap',
 'Mayonnaise',
 'Cleaning Spray',
 'Power Strips',
 'Coffee',
 'Deodorant',
 'Mop',
 'Olive Oil',
 'Shampoo',
 'Hair Gel',
 'Dustpan',
 'Toothbrush',
 'Mustard',
 'Syrup',
 'Lawn Mower',
 nan,
 'Tea',
 'Soap',
 'Tuna',
 'Salmon',
 'Broom',
 'Garden Hose',
 'Bath Towels',
 'Pasta',
 'Orange',
 'Shrimp',
 'Iron',
 'BBQ Sauce',
 'Beef',
 'Hand Sanitizer',
 'Trash Bags',
 'Milk',
 'Bread',
 'Peanut Butter',
 'Jam',
 'Toothpaste',
 'Tissues',
 'Shaving Cream',
 'Dishware',
 'Light Bulbs',
 'Chips',
 'Spinach',
 'Laundry Detergent',
 'Cereal',
 'Onions',
 'Eggs',
 'Cheese',
 'Ketchup',
 'Canned Soup',
 'Air Freshener',
 'Apple',
 'Chicken',
 'Ice Cream',
 'Cleaning Rags',
 'Tomatoes',
 'Vacuum Cleaner',
 'Cereal Bars',
 'Potatoes',
 'Razors',
 'Paper Towels',
 'Pickles',
 'Yogurt',
 'Soda',
 'Insect Repellent',
 'Sponges',
 'Rice',
 'Feminine Hygiene Products',
 'Vinegar',
 'Water',
 'Honey',
 'Butter',
 'Ironing Board']

In [8]:
get_ECLAT_indexes, get_ECLAT_supports = eclat_instance.fit(min_support=0.03,
                                                           min_combination=2,
                                                           max_combination=2,
                                                           separator=' & ',
                                                           verbose=True)

Combination 2 by 2

3240it [00:36, 89.34it/s]

In [9]:
get_ECLAT_supports

{}