Unlike the a priori method, the ECLAT method is not based on the calculation of confidence and lift, therefore the ECLAT method is based on the calculation of the support conjunctions of the variables

https://pypi.org/project/pyECLAT/

In [1]:
import pandas as pd
import ast

In [2]:
dataset = pd.read_csv("Retail_Transactions_Dataset.csv")

dataset.head()

,Transaction_ID,Date,Customer_Name,Product,Total_Items,Total_Cost,Payment_Method,City,Store_Type,Discount_Applied,Customer_Category,Season,Promotion
0,1000000000,2022-01-21 06:27:29,Stacey Price,"['Ketchup', 'Shaving Cream', 'Light Bulbs']",3,71.65,Mobile Payment,Los Angeles,Warehouse Club,True,Homemaker,Winter,NaN
1,1000000001,2023-03-01 13:01:21,Michelle Carlson,"['Ice Cream', 'Milk', 'Olive Oil', 'Bread', 'P...",2,25.93,Cash,San Francisco,Specialty Store,True,Professional,Fall,BOGO (Buy One Get One)
2,1000000002,2024-03-21 15:37:04,Lisa Graves,['Spinach'],6,41.49,Credit Card,Houston,Department Store,True,Professional,Winter,NaN
3,1000000003,2020-10-31 09:59:47,Mrs. Patricia May,"['Tissues', 'Mustard']",1,39.34,Mobile Payment,Chicago,Pharmacy,True,Homemaker,Spring,NaN
4,1000000004,2020-12-10 00:59:59,Susan Mitchell,['Dish Soap'],10,16.42,Debit Card,Houston,Specialty Store,False,Young Adult,Winter,Discount on Selected Items

In [3]:
product_list = dataset["Product"].apply(ast.literal_eval).tolist()

products_dataframe = pd.DataFrame(product_list)

products_dataframe

                 0              1              2        3          4
0          Ketchup  Shaving Cream    Light Bulbs      NaN        NaN
1        Ice Cream           Milk      Olive Oil    Bread   Potatoes
2          Spinach            NaN            NaN      NaN        NaN
3          Tissues        Mustard            NaN      NaN        NaN
4        Dish Soap            NaN            NaN      NaN        NaN
...            ...            ...            ...      ...        ...
999995     Pickles        Carrots  Peanut Butter  Sponges  BBQ Sauce
999996      Cereal            NaN            NaN      NaN        NaN
999997  Trash Bags            NaN            NaN      NaN        NaN
999998     Diapers         Coffee         Coffee      Mop        NaN
999999  Trash Cans            Mop            Jam      NaN        NaN

[1000000 rows x 5 columns]

In [4]:
from pyECLAT import ECLAT

eclat_instance = ECLAT(data=products_dataframe,
                       verbose=True)  #verbose=True to see the loading bar

100%|██████████| 81/81 [00:51<00:00,  1.58it/s]
100%|██████████| 81/81 [00:01<00:00, 48.13it/s]
100%|██████████| 81/81 [00:00<00:00, 110.36it/s]

In [5]:
eclat_instance.df_bin  #generate a binary dataframe, that can be used for other analyzes.
eclat_instance.uniq_  #a list with all the names of the different items

['Dishware',
 'Beef',
 'Eggs',
 'Garden Hose',
 'Canned Soup',
 'Ironing Board',
 'Honey',
 'Syrup',
 'Iron',
 'Tuna',
 'Cleaning Spray',
 'Vinegar',
 'Pancake Mix',
 'Power Strips',
 'Jam',
 'Plant Fertilizer',
 'Deodorant',
 'Toothpaste',
 'Water',
 'Ice Cream',
 'Onions',
 'Spinach',
 'Air Freshener',
 'Trash Bags',
 'Sponges',
 'Chips',
 'Toilet Paper',
 'Potatoes',
 'Butter',
 'Hand Sanitizer',
 'Cleaning Rags',
 'Broom',
 'Paper Towels',
 nan,
 'Pasta',
 'Soap',
 'Bread',
 'Milk',
 'Dish Soap',
 'Shower Gel',
 'BBQ Sauce',
 'Light Bulbs',
 'Soda',
 'Insect Repellent',
 'Carrots',
 'Toothbrush',
 'Dustpan',
 'Vacuum Cleaner',
 'Yogurt',
 'Salmon',
 'Tea',
 'Ketchup',
 'Bath Towels',
 'Rice',
 'Razors',
 'Shrimp',
 'Cereal',
 'Cheese',
 'Apple',
 'Coffee',
 'Mayonnaise',
 'Extension Cords',
 'Baby Wipes',
 'Laundry Detergent',
 'Shampoo',
 'Orange',
 'Mop',
 'Olive Oil',
 'Cereal Bars',
 'Feminine Hygiene Products',
 'Chicken',
 'Shaving Cream',
 'Tissues',
 'Peanut Butter',
 'Banana',
 'Lawn Mower',
 'Tomatoes',
 'Diapers',
 'Pickles',
 'Hair Gel',
 'Mustard',
 'Trash Cans']

In [8]:
get_ECLAT_indexes, get_ECLAT_supports = eclat_instance.fit(min_support=0.001,
                                                           min_combination=2,
                                                           max_combination=2,
                                                           separator=' & ',
                                                           verbose=True)

Combination 2 by 2

3240it [01:10, 45.67it/s]

In [9]:
get_ECLAT_supports

{'Dishware & Beef': 0.001119,
 'Dishware & Eggs': 0.00113,
 'Dishware & Garden Hose': 0.001184,
 'Dishware & Canned Soup': 0.001137,
 'Dishware & Ironing Board': 0.001127,
 'Dishware & Honey': 0.001193,
 'Dishware & Syrup': 0.001157,
 'Dishware & Iron': 0.00113,
 'Dishware & Tuna': 0.00116,
 'Dishware & Cleaning Spray': 0.00114,
 'Dishware & Vinegar': 0.001132,
 'Dishware & Pancake Mix': 0.001153,
 'Dishware & Power Strips': 0.001109,
 'Dishware & Jam': 0.001113,
 'Dishware & Plant Fertilizer': 0.001224,
 'Dishware & Deodorant': 0.001149,
 'Dishware & Toothpaste': 0.002298,
 'Dishware & Water': 0.001122,
 'Dishware & Ice Cream': 0.001149,
 'Dishware & Onions': 0.001172,
 'Dishware & Spinach': 0.001178,
 'Dishware & Air Freshener': 0.001203,
 'Dishware & Trash Bags': 0.001155,
 'Dishware & Sponges': 0.001119,
 'Dishware & Chips': 0.001096,
 'Dishware & Toilet Paper': 0.001151,
 'Dishware & Potatoes': 0.001185,
 'Dishware & Butter': 0.001108,
 'Dishware & Hand Sanitizer': 0.001172,
 'Dishware & Cleaning Rags': 0.001168,
 'Dishware & Broom': 0.001114,
 'Dishware & Paper Towels': 0.001102,
 'Dishware & Pasta': 0.001191,
 'Dishware & Soap': 0.001186,
 'Dishware & Bread': 0.001138,
 'Dishware & Milk': 0.001127,
 'Dishware & Dish Soap': 0.001179,
 'Dishware & Shower Gel': 0.001115,
 'Dishware & BBQ Sauce': 0.001105,
 'Dishware & Light Bulbs': 0.001167,
 'Dishware & Soda': 0.001128,
 'Dishware & Insect Repellent': 0.001126,
 'Dishware & Carrots': 0.001171,
 'Dishware & Toothbrush': 0.001129,
 'Dishware & Dustpan': 0.001128,
 'Dishware & Vacuum Cleaner': 0.001186,
 'Dishware & Yogurt': 0.001067,
 'Dishware & Salmon': 0.001123,
 'Dishware & Tea': 0.001114,
 'Dishware & Ketchup': 0.001144,
 'Dishware & Bath Towels': 0.001163,
 'Dishware & Rice': 0.001169,
 'Dishware & Razors': 0.001147,
 'Dishware & Shrimp': 0.001199,
 'Dishware & Cereal': 0.001191,
 'Dishware & Cheese': 0.0011,
 'Dishware & Apple': 0.001198,
 'Dishware & Coffee': 0.001172,
 'Dishware & Mayonnaise': 0.0011,
 'Dishware & Extension Cords': 0.001086,
 'Dishware & Baby Wipes': 0.00119,
 'Dishware & Laundry Detergent': 0.001154,
 'Dishware & Shampoo': 0.001108,
 'Dishware & Orange': 0.001155,
 'Dishware & Mop': 0.001194,
 'Dishware & Olive Oil': 0.001127,
 'Dishware & Cereal Bars': 0.001212,
 'Dishware & Feminine Hygiene Products': 0.001143,
 'Dishware & Chicken': 0.001126,
 'Dishware & Shaving Cream': 0.001177,
 'Dishware & Tissues': 0.001152,
 'Dishware & Peanut Butter': 0.00114,
 'Dishware & Banana': 0.001105,
 'Dishware & Lawn Mower': 0.001163,
 'Dishware & Tomatoes': 0.001171,
 'Dishware & Diapers': 0.001153,
 'Dishware & Pickles': 0.001157,
 'Dishware & Hair Gel': 0.001153,
 'Dishware & Mustard': 0.00119,
 'Dishware & Trash Cans': 0.001129,
 'Beef & Eggs': 0.001158,
 'Beef & Garden Hose': 0.0012,
 'Beef & Canned Soup': 0.001202,
 'Beef & Ironing Board': 0.001143,
 'Beef & Honey': 0.001245,
 'Beef & Syrup': 0.00122,
 'Beef & Iron': 0.001139,
 'Beef & Tuna': 0.001133,
 'Beef & Cleaning Spray': 0.00113,
 'Beef & Vinegar': 0.001102,
 'Beef & Pancake Mix': 0.001156,
 'Beef & Power Strips': 0.001129,
 'Beef & Jam': 0.001174,
 'Beef & Plant Fertilizer': 0.001136,
 'Beef & Deodorant': 0.001148,
 'Beef & Toothpaste': 0.002305,
 'Beef & Water': 0.001134,
 'Beef & Ice Cream': 0.001239,
 'Beef & Onions': 0.001134,
 'Beef & Spinach': 0.001208,
 'Beef & Air Freshener': 0.001159,
 'Beef & Trash Bags': 0.001161,
 'Beef & Sponges': 0.0012,
 'Beef & Chips': 0.001134,
 'Beef & Toilet Paper': 0.001171,
 'Beef & Potatoes': 0.001112,
 'Beef & Butter': 0.001157,
 'Beef & Hand Sanitizer': 0.001184,
 'Beef & Cleaning Rags': 0.001131,
 'Beef & Broom': 0.001108,
 'Beef & Paper Towels': 0.001124,
 'Beef & Pasta': 0.001193,
 'Beef & Soap': 0.001173,
 'Beef & Bread': 0.001185,
 'Beef & Milk': 0.001137,
 'Beef & Dish Soap': 0.001169,
 'Beef & Shower Gel': 0.001125,
 'Beef & BBQ Sauce': 0.001165,
 'Beef & Light Bulbs': 0.001155,
 'Beef & Soda': 0.001211,
 'Beef & Insect Repellent': 0.001206,
 'Beef & Carrots': 0.001148,
 'Beef & Toothbrush': 0.00118,
 'Beef & Dustpan': 0.001097,
 'Beef & Vacuum Cleaner': 0.001189,
 'Beef & Yogurt': 0.001201,
 'Beef & Salmon': 0.001144,
 'Beef & Tea': 0.001165,
 'Beef & Ketchup': 0.001149,
 'Beef & Bath Towels': 0.001176,
 'Beef & Rice': 0.001196,
 'Beef & Razors': 0.001114,
 'Beef & Shrimp': 0.00113,
 'Beef & Cereal': 0.001193,
 'Beef & Cheese': 0.001195,
 'Beef & Apple': 0.001141,
 'Beef & Coffee': 0.001197,
 'Beef & Mayonnaise': 0.001163,
 'Beef & Extension Cords': 0.001182,
 'Beef & Baby Wipes': 0.001188,
 'Beef & Laundry Detergent': 0.001159,
 'Beef & Shampoo': 0.001145,
 'Beef & Orange': 0.001128,
 'Beef & Mop': 0.001113,
 'Beef & Olive Oil': 0.001153,
 'Beef & Cereal Bars': 0.001123,
 'Beef & Feminine Hygiene Products': 0.001111,
 'Beef & Chicken': 0.001146,
 'Beef & Shaving Cream': 0.00115,
 'Beef & Tissues': 0.001186,
 'Beef & Peanut Butter': 0.001218,
 'Beef & Banana': 0.00111,
 'Beef & Lawn Mower': 0.00115,
 'Beef & Tomatoes': 0.001136,
 'Beef & Diapers': 0.001131,
 'Beef & Pickles': 0.001188,
 'Beef & Hair Gel': 0.001203,
 'Beef & Mustard': 0.001137,
 'Beef & Trash Cans': 0.001184,
 'Eggs & Garden Hose': 0.001168,
 'Eggs & Canned Soup': 0.00116,
 'Eggs & Ironing Board': 0.001124,
 'Eggs & Honey': 0.001187,
 'Eggs & Syrup': 0.001092,
 'Eggs & Iron': 0.001131,
 'Eggs & Tuna': 0.001125,
 'Eggs & Cleaning Spray': 0.001159,
 'Eggs & Vinegar': 0.001135,
 'Eggs & Pancake Mix': 0.001212,
 'Eggs & Power Strips': 0.001135,
 'Eggs & Jam': 0.001159,
 'Eggs & Plant Fertilizer': 0.001138,
 'Eggs & Deodorant': 0.001174,
 'Eggs & Toothpaste': 0.002292,
 'Eggs & Water': 0.001135,
 'Eggs & Ice Cream': 0.001232,
 'Eggs & Onions': 0.001135,
 'Eggs & Spinach': 0.001152,
 'Eggs & Air Freshener': 0.001218,
 'Eggs & Trash Bags': 0.00116,
 'Eggs & Sponges': 0.001172,
 'Eggs & Chips': 0.001172,
 'Eggs & Toilet Paper': 0.001123,
 'Eggs & Potatoes': 0.001189,
 'Eggs & Butter': 0.001167,
 'Eggs & Hand Sanitizer': 0.001177,
 'Eggs & Cleaning Rags': 0.001156,
 'Eggs & Broom': 0.001179,
 'Eggs & Paper Towels': 0.001189,
 'Eggs & Pasta': 0.001128,
 'Eggs & Soap': 0.001171,
 'Eggs & Bread': 0.001155,
 'Eggs & Milk': 0.001168,
 'Eggs & Dish Soap': 0.001149,
 'Eggs & Shower Gel': 0.001119,
 'Eggs & BBQ Sauce': 0.001195,
 'Eggs & Light Bulbs': 0.001131,
 'Eggs & Soda': 0.001171,
 'Eggs & Insect Repellent': 0.001157,
 'Eggs & Carrots': 0.001189,
 'Eggs & Toothbrush': 0.001157,
 'Eggs & Dustpan': 0.001131,
 'Eggs & Vacuum Cleaner': 0.001087,
 'Eggs & Yogurt': 0.00114,
 'Eggs & Salmon': 0.001096,
 'Eggs & Tea': 0.001088,
 'Eggs & Ketchup': 0.001147,
 'Eggs & Bath Towels': 0.001154,
 'Eggs & Rice': 0.001145,
 'Eggs & Razors': 0.001087,
 'Eggs & Shrimp': 0.001098,
 'Eggs & Cereal': 0.00115,
 'Eggs & Cheese': 0.001157,
 'Eggs & Apple': 0.00111,
 'Eggs & Coffee': 0.001177,
 'Eggs & Mayonnaise': 0.001175,
 'Eggs & Extension Cords': 0.001181,
 'Eggs & Baby Wipes': 0.001147,
 'Eggs & Laundry Detergent': 0.001165,
 'Eggs & Shampoo': 0.001144,
 'Eggs & Orange': 0.001141,
 'Eggs & Mop': 0.001162,
 'Eggs & Olive Oil': 0.001114,
 'Eggs & Cereal Bars': 0.001118,
 'Eggs & Feminine Hygiene Products': 0.001189,
 'Eggs & Chicken': 0.001147,
 'Eggs & Shaving Cream': 0.001175,
 'Eggs & Tissues': 0.001126,
 'Eggs & Peanut Butter': 0.00115,
 'Eggs & Banana': 0.001179,
 'Eggs & Lawn Mower': 0.001164,
 'Eggs & Tomatoes': 0.001147,
 'Eggs & Diapers': 0.001185,
 'Eggs & Pickles': 0.001209,
 'Eggs & Hair Gel': 0.001156,
 'Eggs & Mustard': 0.001166,
 'Eggs & Trash Cans': 0.001183,
 'Garden Hose & Canned Soup': 0.001176,
 'Garden Hose & Ironing Board': 0.001138,
 'Garden Hose & Honey': 0.00115,
 'Garden Hose & Syrup': 0.001123,
 'Garden Hose & Iron': 0.001125,
 'Garden Hose & Tuna': 0.001148,
 'Garden Hose & Cleaning Spray': 0.001171,
 'Garden Hose & Vinegar': 0.001106,
 'Garden Hose & Pancake Mix': 0.001158,
 'Garden Hose & Power Strips': 0.001141,
 'Garden Hose & Jam': 0.001141,
 'Garden Hose & Plant Fertilizer': 0.001183,
 'Garden Hose & Deodorant': 0.001195,
 'Garden Hose & Toothpaste': 0.00224,
 'Garden Hose & Water': 0.001203,
 'Garden Hose & Ice Cream': 0.001186,
 'Garden Hose & Onions': 0.001168,
 'Garden Hose & Spinach': 0.001171,
 'Garden Hose & Air Freshener': 0.001129,
 'Garden Hose & Trash Bags': 0.001101,
 'Garden Hose & Sponges': 0.001198,
 'Garden Hose & Chips': 0.001214,
 'Garden Hose & Toilet Paper': 0.001138,
 'Garden Hose & Potatoes': 0.001125,
 'Garden Hose & Butter': 0.00111,
 'Garden Hose & Hand Sanitizer': 0.001158,
 'Garden Hose & Cleaning Rags': 0.001172,
 'Garden Hose & Broom': 0.001131,
 'Garden Hose & Paper Towels': 0.001165,
 'Garden Hose & Pasta': 0.001143,
 'Garden Hose & Soap': 0.001143,
 'Garden Hose & Bread': 0.001141,
 'Garden Hose & Milk': 0.001165,
 'Garden Hose & Dish Soap': 0.001102,
 'Garden Hose & Shower Gel': 0.001119,
 'Garden Hose & BBQ Sauce': 0.001169,
 'Garden Hose & Light Bulbs': 0.00109,
 'Garden Hose & Soda': 0.001217,
 'Garden Hose & Insect Repellent': 0.001191,
 'Garden Hose & Carrots': 0.001157,
 'Garden Hose & Toothbrush': 0.001169,
 'Garden Hose & Dustpan': 0.001108,
 'Garden Hose & Vacuum Cleaner': 0.001197,
 'Garden Hose & Yogurt': 0.001117,
 'Garden Hose & Salmon': 0.001206,
 'Garden Hose & Tea': 0.001201,
 'Garden Hose & Ketchup': 0.001166,
 'Garden Hose & Bath Towels': 0.001147,
 'Garden Hose & Rice': 0.001158,
 'Garden Hose & Razors': 0.001145,
 'Garden Hose & Shrimp': 0.001154,
 'Garden Hose & Cereal': 0.001153,
 'Garden Hose & Cheese': 0.001235,
 'Garden Hose & Apple': 0.001175,
 'Garden Hose & Coffee': 0.001142,
 'Garden Hose & Mayonnaise': 0.001139,
 'Garden Hose & Extension Cords': 0.001252,
 'Garden Hose & Baby Wipes': 0.001189,
 'Garden Hose & Laundry Detergent': 0.001238,
 'Garden Hose & Shampoo': 0.001152,
 'Garden Hose & Orange': 0.001198,
 'Garden Hose & Mop': 0.001146,
 'Garden Hose & Olive Oil': 0.00113,
 'Garden Hose & Cereal Bars': 0.001112,
 'Garden Hose & Feminine Hygiene Products': 0.001192,
 'Garden Hose & Chicken': 0.00117,
 'Garden Hose & Shaving Cream': 0.001185,
 'Garden Hose & Tissues': 0.001143,
 'Garden Hose & Peanut Butter': 0.001137,
 'Garden Hose & Banana': 0.001142,
 'Garden Hose & Lawn Mower': 0.001136,
 'Garden Hose & Tomatoes': 0.001106,
 'Garden Hose & Diapers': 0.001217,
 'Garden Hose & Pickles': 0.001176,
 'Garden Hose & Hair Gel': 0.001127,
 'Garden Hose & Mustard': 0.00119,
 'Garden Hose & Trash Cans': 0.001131,
 'Canned Soup & Ironing Board': 0.001205,
 'Canned Soup & Honey': 0.001191,
 'Canned Soup & Syrup': 0.001149,
 'Canned Soup & Iron': 0.00112,
 'Canned Soup & Tuna': 0.001176,
 'Canned Soup & Cleaning Spray': 0.001132,
 'Canned Soup & Vinegar': 0.00115,
 'Canned Soup & Pancake Mix': 0.001196,
 'Canned Soup & Power Strips': 0.001121,
 'Canned Soup & Jam': 0.001102,
 'Canned Soup & Plant Fertilizer': 0.001088,
 'Canned Soup & Deodorant': 0.001166,
 'Canned Soup & Toothpaste': 0.002323,
 'Canned Soup & Water': 0.001111,
 'Canned Soup & Ice Cream': 0.001147,
 'Canned Soup & Onions': 0.001159,
 'Canned Soup & Spinach': 0.001123,
 'Canned Soup & Air Freshener': 0.001131,
 'Canned Soup & Trash Bags': 0.001132,
 'Canned Soup & Sponges': 0.001169,
 'Canned Soup & Chips': 0.0012,
 'Canned Soup & Toilet Paper': 0.001175,
 'Canned Soup & Potatoes': 0.001153,
 'Canned Soup & Butter': 0.001125,
 'Canned Soup & Hand Sanitizer': 0.001143,
 'Canned Soup & Cleaning Rags': 0.001102,
 'Canned Soup & Broom': 0.001173,
 'Canned Soup & Paper Towels': 0.001179,
 'Canned Soup & Pasta': 0.001111,
 'Canned Soup & Soap': 0.001173,
 'Canned Soup & Bread': 0.00113,
 'Canned Soup & Milk': 0.001167,
 'Canned Soup & Dish Soap': 0.001043,
 'Canned Soup & Shower Gel': 0.001139,
 'Canned Soup & BBQ Sauce': 0.00117,
 'Canned Soup & Light Bulbs': 0.001139,
 'Canned Soup & Soda': 0.001198,
 'Canned Soup & Insect Repellent': 0.001159,
 'Canned Soup & Carrots': 0.00113,
 'Canned Soup & Toothbrush': 0.001134,
 'Canned Soup & Dustpan': 0.001129,
 'Canned Soup & Vacuum Cleaner': 0.001153,
 'Canned Soup & Yogurt': 0.001117,
 'Canned Soup & Salmon': 0.001173,
 'Canned Soup & Tea': 0.0011,
 'Canned Soup & Ketchup': 0.001181,
 'Canned Soup & Bath Towels': 0.001164,
 'Canned Soup & Rice': 0.001162,
 'Canned Soup & Razors': 0.00113,
 'Canned Soup & Shrimp': 0.001141,
 'Canned Soup & Cereal': 0.001102,
 'Canned Soup & Cheese': 0.001126,
 'Canned Soup & Apple': 0.001164,
 'Canned Soup & Coffee': 0.001102,
 'Canned Soup & Mayonnaise': 0.00109,
 'Canned Soup & Extension Cords': 0.001161,
 'Canned Soup & Baby Wipes': 0.00115,
 'Canned Soup & Laundry Detergent': 0.001164,
 'Canned Soup & Shampoo': 0.001119,
 'Canned Soup & Orange': 0.001146,
 'Canned Soup & Mop': 0.001133,
 'Canned Soup & Olive Oil': 0.001145,
 'Canned Soup & Cereal Bars': 0.001138,
 'Canned Soup & Feminine Hygiene Products': 0.001128,
 'Canned Soup & Chicken': 0.001096,
 'Canned Soup & Shaving Cream': 0.001111,
 'Canned Soup & Tissues': 0.001094,
 'Canned Soup & Peanut Butter': 0.001132,
 'Canned Soup & Banana': 0.001127,
 'Canned Soup & Lawn Mower': 0.001121,
 'Canned Soup & Tomatoes': 0.001119,
 'Canned Soup & Diapers': 0.001213,
 'Canned Soup & Pickles': 0.001161,
 'Canned Soup & Hair Gel': 0.001175,
 'Canned Soup & Mustard': 0.001203,
 'Canned Soup & Trash Cans': 0.001164,
 'Ironing Board & Honey': 0.001178,
 'Ironing Board & Syrup': 0.001117,
 'Ironing Board & Iron': 0.00119,
 'Ironing Board & Tuna': 0.001168,
 'Ironing Board & Cleaning Spray': 0.001161,
 'Ironing Board & Vinegar': 0.001168,
 'Ironing Board & Pancake Mix': 0.001137,
 'Ironing Board & Power Strips': 0.001187,
 'Ironing Board & Jam': 0.001155,
 'Ironing Board & Plant Fertilizer': 0.001168,
 'Ironing Board & Deodorant': 0.001146,
 'Ironing Board & Toothpaste': 0.002357,
 'Ironing Board & Water': 0.001138,
 'Ironing Board & Ice Cream': 0.001157,
 'Ironing Board & Onions': 0.001187,
 'Ironing Board & Spinach': 0.0011,
 'Ironing Board & Air Freshener': 0.001201,
 'Ironing Board & Trash Bags': 0.001146,
 'Ironing Board & Sponges': 0.001129,
 'Ironing Board & Chips': 0.00118,
 'Ironing Board & Toilet Paper': 0.001137,
 'Ironing Board & Potatoes': 0.001164,
 'Ironing Board & Butter': 0.001225,
 'Ironing Board & Hand Sanitizer': 0.001179,
 'Ironing Board & Cleaning Rags': 0.001145,
 'Ironing Board & Broom': 0.00116,
 'Ironing Board & Paper Towels': 0.001181,
 'Ironing Board & Pasta': 0.001147,
 'Ironing Board & Soap': 0.001199,
 'Ironing Board & Bread': 0.001178,
 'Ironing Board & Milk': 0.001153,
 'Ironing Board & Dish Soap': 0.0012,
 'Ironing Board & Shower Gel': 0.001146,
 'Ironing Board & BBQ Sauce': 0.001207,
 'Ironing Board & Light Bulbs': 0.00115,
 'Ironing Board & Soda': 0.001194,
 'Ironing Board & Insect Repellent': 0.001204,
 'Ironing Board & Carrots': 0.001129,
 'Ironing Board & Toothbrush': 0.001143,
 'Ironing Board & Dustpan': 0.001163,
 'Ironing Board & Vacuum Cleaner': 0.001137,
 'Ironing Board & Yogurt': 0.001119,
 'Ironing Board & Salmon': 0.001182,
 'Ironing Board & Tea': 0.001171,
 'Ironing Board & Ketchup': 0.001204,
 'Ironing Board & Bath Towels': 0.001189,
 'Ironing Board & Rice': 0.001196,
 'Ironing Board & Razors': 0.00121,
 'Ironing Board & Shrimp': 0.00112,
 'Ironing Board & Cereal': 0.001182,
 'Ironing Board & Cheese': 0.001162,
 'Ironing Board & Apple': 0.001146,
 'Ironing Board & Coffee': 0.001145,
 'Ironing Board & Mayonnaise': 0.001139,
 'Ironing Board & Extension Cords': 0.001178,
 'Ironing Board & Baby Wipes': 0.001217,
 'Ironing Board & Laundry Detergent': 0.001219,
 'Ironing Board & Shampoo': 0.001164,
 'Ironing Board & Orange': 0.001182,
 'Ironing Board & Mop': 0.0011,
 'Ironing Board & Olive Oil': 0.001163,
 'Ironing Board & Cereal Bars': 0.001143,
 'Ironing Board & Feminine Hygiene Products': 0.001161,
 'Ironing Board & Chicken': 0.001152,
 'Ironing Board & Shaving Cream': 0.001224,
 'Ironing Board & Tissues': 0.001175,
 'Ironing Board & Peanut Butter': 0.001209,
 'Ironing Board & Banana': 0.001149,
 'Ironing Board & Lawn Mower': 0.00118,
 'Ironing Board & Tomatoes': 0.001193,
 'Ironing Board & Diapers': 0.001222,
 'Ironing Board & Pickles': 0.001124,
 'Ironing Board & Hair Gel': 0.00117,
 'Ironing Board & Mustard': 0.001125,
 'Ironing Board & Trash Cans': 0.001153,
 'Honey & Syrup': 0.001133,
 'Honey & Iron': 0.001136,
 'Honey & Tuna': 0.001184,
 'Honey & Cleaning Spray': 0.001174,
 'Honey & Vinegar': 0.001166,
 'Honey & Pancake Mix': 0.001122,
 'Honey & Power Strips': 0.001128,
 'Honey & Jam': 0.001152,
 'Honey & Plant Fertilizer': 0.001145,
 'Honey & Deodorant': 0.001204,
 'Honey & Toothpaste': 0.00227,
 'Honey & Water': 0.00116,
 'Honey & Ice Cream': 0.001184,
 'Honey & Onions': 0.001092,
 'Honey & Spinach': 0.001164,
 'Honey & Air Freshener': 0.001197,
 'Honey & Trash Bags': 0.001147,
 'Honey & Sponges': 0.001182,
 'Honey & Chips': 0.001152,
 'Honey & Toilet Paper': 0.001127,
 'Honey & Potatoes': 0.001165,
 'Honey & Butter': 0.001153,
 'Honey & Hand Sanitizer': 0.001157,
 'Honey & Cleaning Rags': 0.001122,
 'Honey & Broom': 0.001123,
 'Honey & Paper Towels': 0.001193,
 'Honey & Pasta': 0.00116,
 'Honey & Soap': 0.001169,
 'Honey & Bread': 0.001168,
 'Honey & Milk': 0.001101,
 'Honey & Dish Soap': 0.001129,
 'Honey & Shower Gel': 0.001135,
 'Honey & BBQ Sauce': 0.001142,
 'Honey & Light Bulbs': 0.001148,
 'Honey & Soda': 0.001241,
 'Honey & Insect Repellent': 0.001152,
 'Honey & Carrots': 0.001223,
 'Honey & Toothbrush': 0.001112,
 'Honey & Dustpan': 0.001106,
 'Honey & Vacuum Cleaner': 0.001125,
 'Honey & Yogurt': 0.001137,
 'Honey & Salmon': 0.001151,
 'Honey & Tea': 0.001247,
 'Honey & Ketchup': 0.001157,
 'Honey & Bath Towels': 0.001135,
 'Honey & Rice': 0.001185,
 'Honey & Razors': 0.001097,
 'Honey & Shrimp': 0.001132,
 'Honey & Cereal': 0.001125,
 'Honey & Cheese': 0.001196,
 'Honey & Apple': 0.001152,
 'Honey & Coffee': 0.001141,
 'Honey & Mayonnaise': 0.001152,
 'Honey & Extension Cords': 0.001128,
 'Honey & Baby Wipes': 0.001133,
 'Honey & Laundry Detergent': 0.001174,
 'Honey & Shampoo': 0.001164,
 'Honey & Orange': 0.001135,
 'Honey & Mop': 0.001214,
 'Honey & Olive Oil': 0.001162,
 'Honey & Cereal Bars': 0.001195,
 'Honey & Feminine Hygiene Products': 0.00116,
 'Honey & Chicken': 0.001156,
 'Honey & Shaving Cream': 0.001128,
 'Honey & Tissues': 0.001195,
 'Honey & Peanut Butter': 0.001109,
 'Honey & Banana': 0.001125,
 'Honey & Lawn Mower': 0.001159,
 'Honey & Tomatoes': 0.001201,
 'Honey & Diapers': 0.00115,
 'Honey & Pickles': 0.001159,
 'Honey & Hair Gel': 0.001227,
 'Honey & Mustard': 0.001184,
 'Honey & Trash Cans': 0.001249,
 'Syrup & Iron': 0.001207,
 'Syrup & Tuna': 0.001129,
 'Syrup & Cleaning Spray': 0.001142,
 'Syrup & Vinegar': 0.001157,
 'Syrup & Pancake Mix': 0.001174,
 'Syrup & Power Strips': 0.00122,
 'Syrup & Jam': 0.001177,
 'Syrup & Plant Fertilizer': 0.001217,
 'Syrup & Deodorant': 0.001123,
 'Syrup & Toothpaste': 0.002282,
 'Syrup & Water': 0.001118,
 'Syrup & Ice Cream': 0.001135,
 'Syrup & Onions': 0.00114,
 'Syrup & Spinach': 0.001159,
 'Syrup & Air Freshener': 0.001154,
 'Syrup & Trash Bags': 0.001125,
 'Syrup & Sponges': 0.00117,
 'Syrup & Chips': 0.001121,
 'Syrup & Toilet Paper': 0.001196,
 'Syrup & Potatoes': 0.001085,
 'Syrup & Butter': 0.001153,
 'Syrup & Hand Sanitizer': 0.001146,
 'Syrup & Cleaning Rags': 0.001169,
 'Syrup & Broom': 0.001145,
 'Syrup & Paper Towels': 0.001126,
 'Syrup & Pasta': 0.001173,
 'Syrup & Soap': 0.001115,
 'Syrup & Bread': 0.001139,
 'Syrup & Milk': 0.001122,
 'Syrup & Dish Soap': 0.001148,
 'Syrup & Shower Gel': 0.00112,
 'Syrup & BBQ Sauce': 0.001146,
 'Syrup & Light Bulbs': 0.001116,
 'Syrup & Soda': 0.001199,
 'Syrup & Insect Repellent': 0.001197,
 'Syrup & Carrots': 0.001192,
 'Syrup & Toothbrush': 0.001176,
 'Syrup & Dustpan': 0.001142,
 'Syrup & Vacuum Cleaner': 0.001221,
 'Syrup & Yogurt': 0.001219,
 'Syrup & Salmon': 0.001197,
 'Syrup & Tea': 0.001121,
 'Syrup & Ketchup': 0.001142,
 'Syrup & Bath Towels': 0.001107,
 'Syrup & Rice': 0.001177,
 'Syrup & Razors': 0.001186,
 'Syrup & Shrimp': 0.001103,