In [1]:
import pandas as pd
import ast

In [2]:
dataset = pd.read_csv("Retail_Transactions_Dataset.csv")

dataset.head()

,Transaction_ID,Date,Customer_Name,Product,Total_Items,Total_Cost,Payment_Method,City,Store_Type,Discount_Applied,Customer_Category,Season,Promotion
0,1000000000,2022-01-21 06:27:29,Stacey Price,"['Ketchup', 'Shaving Cream', 'Light Bulbs']",3,71.65,Mobile Payment,Los Angeles,Warehouse Club,True,Homemaker,Winter,NaN
1,1000000001,2023-03-01 13:01:21,Michelle Carlson,"['Ice Cream', 'Milk', 'Olive Oil', 'Bread', 'P...",2,25.93,Cash,San Francisco,Specialty Store,True,Professional,Fall,BOGO (Buy One Get One)
2,1000000002,2024-03-21 15:37:04,Lisa Graves,['Spinach'],6,41.49,Credit Card,Houston,Department Store,True,Professional,Winter,NaN
3,1000000003,2020-10-31 09:59:47,Mrs. Patricia May,"['Tissues', 'Mustard']",1,39.34,Mobile Payment,Chicago,Pharmacy,True,Homemaker,Spring,NaN
4,1000000004,2020-12-10 00:59:59,Susan Mitchell,['Dish Soap'],10,16.42,Debit Card,Houston,Specialty Store,False,Young Adult,Winter,Discount on Selected Items

In [3]:
product_list = dataset["Product"].apply(ast.literal_eval).tolist()

product_list

[['Ketchup', 'Shaving Cream', 'Light Bulbs'],
 ['Ice Cream', 'Milk', 'Olive Oil', 'Bread', 'Potatoes'],
 ['Spinach'],
 ['Tissues', 'Mustard'],
 ['Dish Soap'],
 ['Toothpaste', 'Chicken'],
 ['Honey', 'BBQ Sauce', 'Soda', 'Olive Oil', 'Garden Hose'],
 ['Syrup', 'Trash Cans', 'Pancake Mix', 'Water', 'Mayonnaise'],
 ['Insect Repellent'],
 ['Soap', 'Baby Wipes', 'Soda'],
 ['Extension Cords', 'Soda', 'Water', 'Garden Hose', 'Cleaning Spray'],
 ['Tea', 'Paper Towels', 'Spinach'],
 ['Salmon', 'Shaving Cream'],
 ['Trash Bags', 'Apple', 'Mop', 'Hair Gel'],
 ['Razors', 'Laundry Detergent', 'Beef'],
 ['Cereal', 'Vinegar', 'Bath Towels'],
 ['Air Freshener', 'Feminine Hygiene Products'],
 ['Power Strips', 'Honey', 'Ketchup', 'Tea', 'Shampoo'],
 ['Mustard', 'Dustpan'],
 ['Coffee'],
 ['Pancake Mix', 'Vacuum Cleaner'],
 ['Coffee', 'Shaving Cream'],
 ['Shrimp', 'Iron', 'Cleaning Spray', 'Toilet Paper', 'Peanut Butter'],
 ['Dishware', 'Pickles'],
 ['Sponges', 'Vacuum Cleaner', 'Iron'],
 ['Broom', 'Cereal'],
 ['Garden Hose', 'Trash Cans'],
 ['Ketchup', 'Trash Cans', 'Toothbrush'],
 ['Tomatoes', 'Salmon'],
 ['Tea', 'Salmon', 'Bath Towels', 'Toothpaste'],
 ['Olive Oil'],
 ['Extension Cords', 'Razors', 'Chips', 'Shampoo'],
 ['Apple', 'Butter'],
 ['Broom', 'Chicken', 'Spinach', 'Broom'],
 ['Yogurt', 'Ice Cream', 'Insect Repellent'],
 ['Onions', 'Dish Soap'],
 ['Tomatoes', 'Mustard', 'Apple', 'Hair Gel'],
 ['Garden Hose'],
 ['Shower Gel', 'Dish Soap', 'Plant Fertilizer', 'Garden Hose', 'Tuna'],
 ['Potatoes', 'Air Freshener', 'Sponges', 'Onions', 'Laundry Detergent'],
 ['Feminine Hygiene Products'],
 ['Shaving Cream', 'Butter'],
 ['Lawn Mower', 'Eggs', 'Dustpan', 'Peanut Butter', 'Beef'],
 ['Dustpan', 'BBQ Sauce', 'Toothbrush', 'Deodorant', 'Dish Soap'],
 ['Bread', 'Dustpan', 'Ketchup', 'Ironing Board'],
 ['Soap'],
 ['Razors'],
 ['Pasta', 'Olive Oil'],
 ['Beef', 'Milk', 'Salmon', 'Shampoo'],
 ['Tea'],
 ['Hand Sanitizer',
  'Plant Fertilizer',
  'Baby Wipes',
  'Hand Sanitizer',
  'Power Strips'],
 ['Bread'],
 ['Vacuum Cleaner', 'Apple', 'Shrimp', 'Trash Bags', 'Carrots'],
 ['Shrimp', 'Cleaning Rags', 'Olive Oil', 'Soda'],
 ['Olive Oil',
  'Feminine Hygiene Products',
  'Toothpaste',
  'Soap',
  'Bath Towels'],
 ['Peanut Butter'],
 ['Orange'],
 ['Syrup', 'Tuna', 'Paper Towels', 'Toothpaste', 'Mustard'],
 ['Laundry Detergent', 'BBQ Sauce'],
 ['Dish Soap', 'Shower Gel', 'Lawn Mower', 'Dustpan', 'Toothpaste'],
 ['Dustpan', 'Bath Towels', 'Pickles', 'Sponges'],
 ['Milk', 'Tuna', 'Ketchup', 'Broom'],
 ['Beef', 'Bread', 'Dustpan'],
 ['Pancake Mix', 'Dustpan', 'Laundry Detergent', 'Garden Hose'],
 ['Cereal Bars', 'Air Freshener', 'Honey', 'Laundry Detergent'],
 ['Banana', 'Garden Hose', 'Extension Cords', 'Toothpaste', 'Syrup'],
 ['Shrimp'],
 ['Broom', 'Pickles', 'Cleaning Rags'],
 ['Peanut Butter', 'Lawn Mower', 'Syrup', 'Chicken', 'Toothpaste'],
 ['Peanut Butter', 'Razors'],
 ['Mop', 'Laundry Detergent', 'Vacuum Cleaner'],
 ['Eggs', 'Shower Gel', 'Olive Oil'],
 ['Vinegar'],
 ['Shaving Cream', 'Apple', 'Pickles'],
 ['Canned Soup', 'Tea'],
 ['Syrup', 'Salmon'],
 ['Peanut Butter'],
 ['Hair Gel', 'Tomatoes', 'Cheese', 'Power Strips', 'Beef'],
 ['Light Bulbs', 'Tissues'],
 ['Olive Oil', 'Banana'],
 ['Mop', 'Jam', 'Cheese', 'Hand Sanitizer'],
 ['Diapers', 'Light Bulbs', 'Soda', 'Toothpaste'],
 ['Light Bulbs', 'Hair Gel', 'Mustard', 'Iron'],
 ['Hand Sanitizer', 'Dish Soap', 'Deodorant', 'Cereal'],
 ['Ketchup', 'Toothpaste'],
 ['Toothpaste', 'Dishware', 'Bread', 'Eggs'],
 ['Iron', 'Plant Fertilizer', 'Eggs', 'Pickles'],
 ['Air Freshener', 'Chicken', 'Shaving Cream'],
 ['Plant Fertilizer', 'Tuna', 'Orange'],
 ['Mop'],
 ['Baby Wipes'],
 ['Beef', 'Cleaning Spray', 'Sponges'],
 ['Tissues', 'Cheese', 'Toilet Paper', 'Cereal Bars', 'Cereal Bars'],
 ['Water', 'Olive Oil'],
 ['Banana', 'Toothpaste', 'Iron'],
 ['Potatoes', 'Cleaning Spray'],
 ['Cleaning Rags', 'Syrup', 'BBQ Sauce'],
 ['Dish Soap', 'Apple'],
 ['Salmon', 'Dustpan', 'Yogurt'],
 ['Eggs'],
 ['Deodorant'],
 ['Canned Soup'],
 ['Soda', 'Laundry Detergent', 'Vinegar', 'Toothbrush'],
 ['Bath Towels', 'Canned Soup'],
 ['Air Freshener', 'Tuna', 'Onions', 'Baby Wipes'],
 ['Trash Bags', 'Feminine Hygiene Products', 'Lawn Mower', 'Ice Cream'],
 ['Tuna', 'Coffee', 'Trash Cans'],
 ['Sponges', 'Cleaning Rags', 'Razors', 'Tuna'],
 ['Razors', 'Light Bulbs', 'Trash Cans', 'Honey'],
 ['Mustard', 'Soap', 'Bread', 'Pasta', 'Shaving Cream'],
 ['Chips', 'Canned Soup', 'Cleaning Spray', 'Olive Oil'],
 ['Air Freshener',
  'Laundry Detergent',
  'Cleaning Spray',
  'Shaving Cream',
  'Ketchup'],
 ['Tissues', 'Insect Repellent', 'Bread', 'Pancake Mix'],
 ['Feminine Hygiene Products', 'Pickles'],
 ['Pasta', 'Orange'],
 ['Shower Gel', 'Pickles', 'Bread', 'Sponges'],
 ['Apple'],
 ['Spinach', 'Chips', 'Diapers', 'Tissues'],
 ['Yogurt', 'Power Strips'],
 ['Extension Cords', 'Insect Repellent'],
 ['Cleaning Spray', 'Trash Cans'],
 ['Vacuum Cleaner', 'Spinach'],
 ['Shampoo'],
 ['Bath Towels', 'Feminine Hygiene Products'],
 ['Ketchup', 'Eggs', 'Mop', 'Mop'],
 ['Pasta', 'Coffee', 'Canned Soup'],
 ['Canned Soup', 'Toothpaste', 'Olive Oil'],
 ['Soap', 'Trash Cans', 'Shampoo', 'Hair Gel', 'Eggs'],
 ['Paper Towels'],
 ['Rice', 'Broom', 'Insect Repellent', 'Shower Gel'],
 ['Tea', 'Ironing Board'],
 ['Hand Sanitizer', 'Tomatoes', 'Yogurt', 'Hair Gel'],
 ['Carrots', 'Extension Cords'],
 ['Carrots', 'Ice Cream', 'Orange', 'Hair Gel'],
 ['Hair Gel', 'Toothpaste', 'Dish Soap', 'Sponges', 'Spinach'],
 ['Insect Repellent', 'Peanut Butter', 'Potatoes', 'Tissues', 'Trash Cans'],
 ['Feminine Hygiene Products', 'Ironing Board', 'Power Strips', 'Tomatoes'],
 ['Ketchup', 'Power Strips', 'Dustpan'],
 ['BBQ Sauce', 'Tuna', 'Honey'],
 ['Tuna', 'Toilet Paper'],
 ['Cheese', 'Shaving Cream'],
 ['Coffee', 'Laundry Detergent', 'Jam'],
 ['Deodorant', 'Ironing Board', 'Spinach'],
 ['Ketchup', 'Razors', 'Shaving Cream'],
 ['Dish Soap', 'Ironing Board', 'Carrots', 'Light Bulbs'],
 ['Hand Sanitizer'],
 ['Laundry Detergent', 'BBQ Sauce', 'Butter', 'Garden Hose', 'Paper Towels'],
 ['Peanut Butter', 'Coffee'],
 ['Chips', 'Broom', 'Paper Towels'],
 ['Orange', 'Orange'],
 ['Potatoes', 'Light Bulbs', 'Toothbrush'],
 ['Pancake Mix', 'Cheese', 'Insect Repellent', 'Beef', 'Bread'],
 ['Onions'],
 ['Air Freshener', 'Sponges'],
 ['Air Freshener'],
 ['Spinach'],
 ['Tea', 'Soda'],
 ['Cereal Bars', 'Paper Towels', 'Orange'],
 ['Hair Gel', 'Trash Bags', 'Power Strips', 'Feminine Hygiene Products'],
 ['Paper Towels'],
 ['Water', 'Mop'],
 ['Tissues', 'Jam'],
 ['Olive Oil'],
 ['Plant Fertilizer', 'Shower Gel', 'Tuna'],
 ['Pickles', 'Cleaning Spray'],
 ['BBQ Sauce', 'Eggs', 'Shrimp'],
 ['Trash Cans', 'Toothpaste', 'Broom', 'Baby Wipes', 'Tea'],
 ['Power Strips'],
 ['Toothbrush', 'Toothbrush', 'BBQ Sauce', 'Dustpan', 'Banana'],
 ['Bread', 'Toothpaste', 'Syrup', 'Ironing Board', 'Cleaning Spray'],
 ['Onions', 'Peanut Butter', 'Tomatoes', 'Mayonnaise'],
 ['Syrup', 'Tuna'],
 ['Power Strips', 'Eggs', 'Butter', 'Onions'],
 ['Tissues', 'Spinach', 'Light Bulbs'],
 ['Mustard', 'Trash Cans'],
 ['Honey', 'Cereal Bars', 'Sponges', 'Olive Oil'],
 ['BBQ Sauce', 'Cleaning Spray', 'Broom'],
 ['Trash Bags', 'Extension Cords', 'Beef'],
 ['Onions'],
 ['Honey', 'Salmon', 'Diapers', 'Hair Gel'],
 ['Canned Soup', 'Deodorant', 'Banana', 'Chips', 'Shampoo'],
 ['BBQ Sauce', 'Garden Hose', 'Hair Gel'],
 ['Vinegar', 'Soap'],
 ['Toothpaste', 'Jam', 'Tissues'],
 ['Mustard'],
 ['Ice Cream', 'Ice Cream', 'Laundry Detergent'],
 ['Toothpaste', 'Paper Towels'],
 ['Carrots', 'Air Freshener', 'Butter', 'Cleaning Spray'],
 ['Bath Towels', 'Vinegar'],
 ['Dish Soap'],
 ['Shrimp', 'Chips'],
 ['Paper Towels', 'Cleaning Rags'],
 ['Yogurt', 'Iron', 'Shaving Cream', 'Hand Sanitizer'],
 ['Chicken', 'Paper Towels', 'Cleaning Rags', 'Razors', 'Power Strips'],
 ['Air Freshener', 'Iron', 'Ice Cream', 'Ketchup'],
 ['Shampoo', 'Beef'],
 ['Paper Towels', 'Trash Cans', 'Dustpan', 'Syrup', 'Iron'],
 ['Shrimp', 'Feminine Hygiene Products', 'Toilet Paper', 'Water'],
 ['Pasta', 'Shampoo'],
 ['Garden Hose', 'Cheese', 'Bath Towels'],
 ['Honey', 'Yogurt', 'Potatoes', 'Apple', 'Onions'],
 ['Shower Gel', 'Onions'],
 ['Peanut Butter', 'Diapers'],
 ['Cereal Bars', 'Tomatoes'],
 ['Sponges'],
 ['Chips', 'Shampoo', 'Trash Bags', 'Soap', 'Dishware'],
 ['Garden Hose'],
 ['Spinach', 'Feminine Hygiene Products', 'Onions', 'BBQ Sauce'],
 ['Paper Towels', 'Toothpaste'],
 ['Mustard', 'Chicken', 'Bread'],
 ['Pasta', 'Carrots', 'Power Strips', 'Shrimp'],
 ['Onions', 'Plant Fertilizer', 'Ice Cream', 'Tuna'],
 ['Paper Towels', 'Rice', 'Mayonnaise', 'Pickles', 'Mayonnaise'],
 ['Carrots', 'Orange', 'Paper Towels', 'Soap'],
 ['Shaving Cream', 'Dustpan', 'Rice', 'Orange', 'Honey'],
 ['Coffee', 'Hair Gel', 'Vacuum Cleaner'],
 ['Pancake Mix', 'Water', 'Air Freshener', 'Tea'],
 ['Butter', 'Onions', 'Diapers'],
 ['Milk', 'Insect Repellent', 'BBQ Sauce', 'BBQ Sauce', 'Hair Gel'],
 ['Trash Bags', 'Cleaning Rags'],
 ['Butter', 'Ketchup'],
 ['Ketchup'],
 ['Baby Wipes'],
 ['Toothpaste'],
 ['Banana', 'Feminine Hygiene Products'],
 ['Vacuum Cleaner', 'Ironing Board', 'Olive Oil', 'Tea', 'Shrimp'],
 ['Mayonnaise'],
 ['Shaving Cream',
  'Power Strips',
  'Laundry Detergent',
  'Orange',
  'Hand Sanitizer'],
 ['Rice', 'Ketchup'],
 ['Broom'],
 ['Onions', 'Salmon'],
 ['Potatoes', 'Pancake Mix', 'Peanut Butter', 'Jam'],
 ['Shower Gel', 'Peanut Butter', 'Baby Wipes', 'Hair Gel'],
 ['Laundry Detergent', 'Hand Sanitizer'],
 ['Light Bulbs', 'Plant Fertilizer', 'Bath Towels', 'Cleaning Rags'],
 ['Soap', 'Banana', 'Tea', 'Feminine Hygiene Products', 'Mustard'],
 ['Water', 'Toothbrush'],
 ['Cleaning Spray', 'Eggs', 'Olive Oil', 'Baby Wipes', 'Shrimp'],
 ['Deodorant', 'BBQ Sauce', 'Trash Cans'],
 ['Bread'],
 ['Syrup', 'Tomatoes'],
 ['Shaving Cream', 'Laundry Detergent', 'BBQ Sauce', 'Air Freshener'],
 ['Shrimp', 'Orange', 'Tomatoes', 'Soda', 'Deodorant'],
 ['Sponges', 'Chicken', 'Syrup', 'Cleaning Spray', 'Honey'],
 ['Tomatoes', 'Laundry Detergent'],
 ['Shaving Cream', 'Mustard'],
 ['Insect Repellent', 'Shaving Cream', 'Shampoo', 'Sponges'],
 ['Olive Oil', 'Dish Soap', 'Dish Soap'],
 ['Milk', 'Tuna', 'Honey', 'Shower Gel'],
 ['Extension Cords'],
 ['Bread', 'Deodorant', 'Banana'],
 ['Razors', 'Coffee', 'Vinegar', 'Chips', 'Chips'],
 ['Cleaning Rags', 'Pickles', 'Shaving Cream', 'Mustard'],
 ['Cereal Bars'],
 ['Trash Bags', 'Trash Bags', 'Pickles'],
 ['Shrimp'],
 ['Milk', 'Hair Gel'],
 ['Toothpaste', 'Soda', 'Toothbrush'],
 ['Trash Cans', 'Razors'],
 ['Insect Repellent'],
 ['Lawn Mower'],
 ['Spinach'],
 ['Insect Repellent', 'Dishware', 'Apple'],
 ['Soap', 'Dish Soap', 'Chips', 'Tea'],
 ['Garden Hose', 'Milk', 'Lawn Mower'],
 ['Light Bulbs', 'Honey', 'Bath Towels', 'Cereal Bars', 'Rice'],
 ['Plant Fertilizer', 'Vacuum Cleaner'],
 ['Insect Repellent', 'Hand Sanitizer', 'Honey', 'Dish Soap', 'Pickles'],
 ['Cleaning Spray', 'Cereal Bars'],
 ['Mayonnaise', 'Tissues', 'Potatoes', 'Salmon'],
 ['Milk', 'Banana'],
 ['Syrup', 'Spinach', 'Ironing Board'],
 ['Sponges', 'Shrimp', 'Soda'],
 ['Eggs', 'Paper Towels'],
 ['Toothpaste', 'Bath Towels', 'Carrots'],
 ['Insect Repellent', 'Power Strips', 'Toothbrush', 'Yogurt'],
 ['Pancake Mix', 'Mop'],
 ['Hand Sanitizer', 'Mustard', 'Toilet Paper', 'Water'],
 ['Syrup'],
 ['Shaving Cream', 'Jam'],
 ['Ketchup', 'Hand Sanitizer', 'Orange', 'Vacuum Cleaner'],
 ['Dishware', 'Soap'],
 ['Ice Cream', 'Cereal', 'Feminine Hygiene Products', 'Ice Cream', 'Coffee'],
 ['Pasta', 'Toilet Paper', 'Chips', 'Light Bulbs', 'Toilet Paper'],
 ['Pancake Mix', 'Cereal'],
 ['Cereal Bars', 'Cleaning Rags', 'Chips', 'Hand Sanitizer', 'Deodorant'],
 ['Peanut Butter', 'Vacuum Cleaner', 'Milk'],
 ['Shampoo', 'Tuna', 'Shaving Cream', 'Dustpan'],
 ['Trash Bags', 'Vinegar', 'Banana', 'Pickles', 'Ketchup'],
 ['Mop', 'Soap'],
 ['Hand Sanitizer'],
 ['Lawn Mower'],
 ['Cereal', 'Honey', 'Carrots', 'Cheese', 'Broom'],
 ['Chips', 'Cleaning Spray', 'Iron', 'Carrots', 'Shaving Cream'],
 ['Iron', 'Butter', 'Shower Gel', 'Broom'],
 ['Milk', 'Extension Cords', 'Mayonnaise', 'Hand Sanitizer'],
 ['Mop', 'Ketchup', 'Tomatoes', 'Spinach'],
 ['Eggs'],
 ['Tea', 'Cereal', 'Honey', 'Cleaning Spray', 'Ketchup'],
 ['Bath Towels', 'Beef', 'Tomatoes'],
 ['Shampoo', 'Tuna', 'Olive Oil', 'Peanut Butter', 'Carrots'],
 ['BBQ Sauce', 'Power Strips'],
 ['Paper Towels', 'Shrimp', 'Feminine Hygiene Products', 'Dishware'],
 ['Beef', 'Hand Sanitizer', 'Mayonnaise', 'Rice'],
 ['Toothbrush', 'Hand Sanitizer'],
 ['Coffee'],
 ['Toothpaste'],
 ['Banana', 'Canned Soup'],
 ['Olive Oil', 'Diapers'],
 ['Shrimp', 'Pancake Mix'],
 ['Salmon', 'Plant Fertilizer', 'Cleaning Spray', 'Apple'],
 ['Shaving Cream'],
 ['Deodorant'],
 ['Laundry Detergent'],
 ['Tuna', 'Chips', 'Chicken', 'Potatoes', 'Dustpan'],
 ['Soap'],
 ['Soap', 'Cheese', 'Eggs', 'Cleaning Spray', 'Ketchup'],
 ['Garden Hose'],
 ['Shampoo', 'Salmon', 'Soda'],
 ['Vacuum Cleaner', 'Garden Hose', 'Tea'],
 ['Soap', 'Iron'],
 ['Feminine Hygiene Products'],
 ['Dish Soap', 'Lawn Mower'],
 ['Bread', 'Mop', 'Ketchup', 'Chicken', 'Tuna'],
 ['Ketchup', 'Garden Hose'],
 ['Light Bulbs'],
 ['Beef', 'Yogurt', 'Garden Hose'],
 ['Dustpan'],
 ['Trash Cans', 'Shampoo', 'Diapers', 'Diapers'],
 ['Onions', 'Vinegar', 'Cleaning Rags', 'Ketchup'],
 ['Mustard', 'Shrimp', 'Shampoo', 'Feminine Hygiene Products'],
 ['Deodorant', 'Paper Towels'],
 ['Soap'],
 ['Shower Gel', 'Pickles', 'Salmon', 'Extension Cords', 'Lawn Mower'],
 ['Insect Repellent',
  'Canned Soup',
  'Ironing Board',
  'Vinegar',
  'Peanut Butter'],
 ['Canned Soup'],
 ['Hand Sanitizer', 'Ice Cream', 'Tea'],
 ['Mop', 'Shrimp', 'Shrimp', 'Cleaning Rags'],
 ['Olive Oil', 'Chips', 'Apple', 'Iron'],
 ['Bath Towels'],
 ['Ironing Board', 'Pasta'],
 ['Tuna'],
 ['Dish Soap'],
 ['Salmon', 'Tea', 'Yogurt'],
 ['Mustard', 'Vinegar', 'Light Bulbs', 'Cleaning Spray'],
 ['Bread', 'Syrup', 'Laundry Detergent'],
 ['Mustard'],
 ['Apple'],
 ['Hand Sanitizer', 'Honey', 'Hair Gel', 'Feminine Hygiene Products', 'Honey'],
 ['Extension Cords', 'Milk', 'Razors', 'Lawn Mower', 'Milk'],
 ['Cereal Bars', 'Vacuum Cleaner', 'Coffee', 'Onions', 'Cleaning Spray'],
 ['Lawn Mower', 'Soda', 'Beef', 'Shampoo'],
 ['Toothpaste', 'Air Freshener', 'Toothpaste'],
 ['Plant Fertilizer', 'Hand Sanitizer', 'Potatoes', 'Shower Gel'],
 ['Hand Sanitizer'],
 ['Mop', 'Shower Gel', 'Cheese'],
 ['Shampoo', 'Shampoo'],
 ['Pancake Mix', 'Toilet Paper', 'Paper Towels'],
 ['Olive Oil', 'Tea'],
 ['Beef', 'Onions'],
 ['Beef', 'Olive Oil'],
 ['Baby Wipes'],
 ['Toothpaste', 'Vacuum Cleaner', 'Mayonnaise', 'Ketchup'],
 ['Dustpan', 'Peanut Butter'],
 ['Mop', 'Toothpaste'],
 ['Honey', 'Chips', 'Pickles', 'Shampoo', 'Milk'],
 ['Extension Cords'],
 ['Honey', 'Mop', 'Spinach', 'Feminine Hygiene Products'],
 ['Ironing Board', 'Toothbrush', 'Toothpaste'],
 ['Insect Repellent', 'Lawn Mower'],
 ['Apple'],
 ['Toilet Paper'],
 ['Laundry Detergent'],
 ['Paper Towels', 'Onions', 'Water'],
 ['Potatoes', 'Yogurt', 'Toothpaste', 'Carrots'],
 ['Cheese', 'Cleaning Spray', 'Insect Repellent', 'Beef'],
 ['Chicken', 'Toothpaste', 'Pickles', 'Laundry Detergent'],
 ['Apple', 'Dustpan', 'Plant Fertilizer', 'Trash Bags', 'Trash Cans'],
 ['Tomatoes', 'Yogurt', 'Vinegar', 'Cheese'],
 ['Shrimp', 'Peanut Butter', 'Vinegar', 'Beef', 'Hand Sanitizer'],
 ['Hair Gel', 'Dish Soap', 'Rice', 'Salmon'],
 ['Shaving Cream', 'Spinach', 'Deodorant'],
 ['Toothbrush', 'Plant Fertilizer'],
 ['Orange'],
 ['Sponges',
  'Air Freshener',
  'Banana',
  'Feminine Hygiene Products',
  'Shaving Cream'],
 ['Cleaning Rags', 'Jam', 'Cheese', 'Carrots'],
 ['Tuna', 'Baby Wipes', 'Carrots'],
 ['Plant Fertilizer', 'Pickles', 'Olive Oil', 'Pancake Mix', 'Deodorant'],
 ['Razors', 'Extension Cords', 'Orange', 'Ice Cream', 'Pasta'],
 ['Bath Towels', 'Rice', 'Cleaning Rags'],
 ['Salmon'],
 ['Canned Soup', 'Cheese', 'Beef'],
 ['Toothpaste'],
 ['Potatoes', 'Toothbrush'],
 ['Shower Gel', 'Shampoo', 'Dishware'],
 ['Tea', 'Beef', 'Coffee'],
 ['Olive Oil', 'Banana', 'Orange', 'Coffee'],
 ['Bread', 'Bread', 'Trash Cans', 'Beef'],
 ['Eggs'],
 ['Rice'],
 ['Toothpaste', 'Extension Cords', 'Lawn Mower', 'Yogurt'],
 ['Trash Bags'],
 ['Broom'],
 ['Tea', 'Garden Hose', 'Lawn Mower', 'Butter', 'Broom'],
 ['Orange'],
 ['Canned Soup'],
 ['Pasta', 'Tissues', 'Canned Soup', 'Ice Cream'],
 ['Ice Cream',
  'Shower Gel',
  'Toothpaste',
  'Laundry Detergent',
  'Vacuum Cleaner'],
 ['Shaving Cream', 'Mustard', 'Peanut Butter', 'Toothpaste', 'Toothbrush'],
 ['BBQ Sauce'],
 ['Mustard', 'Bread', 'Chicken', 'Pickles', 'Bread'],
 ['BBQ Sauce', 'Syrup'],
 ['Power Strips', 'Plant Fertilizer'],
 ['Mustard', 'Bath Towels'],
 ['Ironing Board'],
 ['Dustpan', 'Soap', 'Banana', 'Shower Gel'],
 ['Soda', 'Carrots', 'Water', 'Razors', 'Cleaning Rags'],
 ['Onions', 'Dishware', 'Hair Gel'],
 ['Hand Sanitizer', 'Razors'],
 ['Apple', 'Water'],
 ['Baby Wipes'],
 ['Baby Wipes', 'Razors', 'Feminine Hygiene Products'],
 ['Hand Sanitizer', 'Onions', 'Tissues', 'Yogurt'],
 ['Feminine Hygiene Products', 'Olive Oil'],
 ['Vacuum Cleaner', 'Trash Bags', 'Sponges'],
 ['Banana', 'Air Freshener'],
 ['Soap', 'Shampoo', 'Pancake Mix'],
 ['Canned Soup', 'Chips', 'Dishware', 'Air Freshener'],
 ['Broom'],
 ['Bread', 'Mayonnaise'],
 ['Eggs', 'Cheese'],
 ['Apple', 'Power Strips', 'Pickles'],
 ['Cereal Bars', 'Rice'],
 ['Extension Cords', 'Soap', 'Toothpaste', 'Ice Cream'],
 ['Deodorant',
  'Bath Towels',
  'Shaving Cream',
  'Feminine Hygiene Products',
  'Water'],
 ['Tuna', 'Banana', 'Cleaning Rags', 'Hand Sanitizer'],
 ['Insect Repellent'],
 ['Eggs', 'Dustpan', 'Soda'],
 ['Trash Cans', 'Chips'],
 ['Insect Repellent',
  'Vacuum Cleaner',
  'Extension Cords',
  'Canned Soup',
  'Air Freshener'],
 ['Vacuum Cleaner', 'Iron', 'Shampoo'],
 ['Salmon', 'Ironing Board', 'Hand Sanitizer', 'Milk'],
 ['Mop'],
 ['Hair Gel', 'Tuna', 'Banana'],
 ['Bread', 'Spinach', 'Trash Bags'],
 ['Baby Wipes', 'Cleaning Rags', 'Toothbrush'],
 ['Peanut Butter'],
 ['Soap', 'Tuna', 'Broom', 'Mop'],
 ['Laundry Detergent', 'Pasta'],
 ['Tuna', 'Hand Sanitizer'],
 ['Pasta', 'Cleaning Rags'],
 ['Soda', 'Orange'],
 ['Diapers', 'Laundry Detergent'],
 ['Feminine Hygiene Products', 'Toothpaste', 'Dustpan', 'Razors'],
 ['Carrots', 'Baby Wipes', 'Dustpan', 'Canned Soup'],
 ['Light Bulbs', 'Coffee'],
 ['Tissues', 'Dish Soap', 'Water', 'Tissues', 'Chips'],
 ['Vinegar'],
 ['Insect Repellent'],
 ['Chicken'],
 ['Rice', 'Extension Cords', 'Bread'],
 ['Cleaning Spray', 'Water', 'Butter', 'Baby Wipes', 'Soap'],
 ['Peanut Butter', 'Trash Cans', 'Banana'],
 ['Hand Sanitizer', 'Deodorant', 'Coffee'],
 ['Canned Soup', 'Water', 'Chips', 'Toothpaste', 'Banana'],
 ['BBQ Sauce', 'Chicken', 'Tuna'],
 ['Sponges', 'Yogurt'],
 ['Milk'],
 ['Beef', 'Shower Gel'],
 ['Soap'],
 ['Toothbrush', 'Banana', 'Pancake Mix', 'Carrots', 'Pasta'],
 ['Power Strips', 'Shower Gel'],
 ['Mop', 'Shaving Cream'],
 ['Olive Oil'],
 ['Honey', 'Chips'],
 ['Cereal', 'Trash Bags', 'Iron', 'Shampoo'],
 ['Soap', 'Toothpaste'],
 ['Iron', 'Light Bulbs', 'Pancake Mix', 'Yogurt', 'Tissues'],
 ['Mayonnaise'],
 ['Cereal Bars', 'Mayonnaise', 'Mayonnaise', 'Banana'],
 ['Trash Cans', 'Toothpaste'],
 ['Light Bulbs', 'Jam'],
 ['Ketchup', 'Olive Oil', 'Lawn Mower'],
 ['Feminine Hygiene Products', 'Deodorant'],
 ['Feminine Hygiene Products',
  'Plant Fertilizer',
  'Spinach',
  'Cleaning Spray'],
 ['Dustpan', 'Razors', 'Mop'],
 ['Olive Oil', 'Lawn Mower', 'Toothpaste'],
 ['Mustard', 'Cleaning Rags', 'Iron', 'Toothbrush', 'Hand Sanitizer'],
 ['Baby Wipes', 'Insect Repellent'],
 ['Shaving Cream', 'Air Freshener', 'Mop', 'Butter', 'Chips'],
 ['Pasta', 'Orange', 'Extension Cords'],
 ['Pickles'],
 ['Dish Soap'],
 ['Pasta', 'Ketchup', 'Bread', 'Butter', 'Soda'],
 ['Pasta', 'Carrots', 'Butter'],
 ['Toothpaste', 'Mustard', 'Dishware', 'Cereal Bars'],
 ['Mop', 'Honey', 'Iron', 'Diapers'],
 ['Carrots'],
 ['Ironing Board', 'Feminine Hygiene Products', 'Bath Towels', 'Jam'],
 ['Cereal Bars', 'Tomatoes', 'Toothpaste', 'Honey', 'Shampoo'],
 ['Ketchup', 'Tea'],
 ['Mayonnaise', 'Toothpaste', 'Vinegar'],

In [4]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(product_list).transform(product_list)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Air Freshener,Apple,BBQ Sauce,Baby Wipes,Banana,Bath Towels,Beef,Bread,Broom,Butter,...,Tomatoes,Toothbrush,Toothpaste,Trash Bags,Trash Cans,Tuna,Vacuum Cleaner,Vinegar,Water,Yogurt
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
999998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False

In [6]:
from mlxtend.frequent_patterns import fpgrowth

support_Two_items = fpgrowth(df, min_support=0.001, use_colnames=True)

support_two_items = support_Two_items[support_Two_items['itemsets'].apply(
    lambda x: len(x) == 2)]
display(support_two_items)

       support                                    itemsets
81    0.001193   frozenset({Shaving Cream, Air Freshener})
82    0.001243         frozenset({Shaving Cream, Mustard})
83    0.001204            frozenset({Shaving Cream, Soap})
84    0.001108           frozenset({Shaving Cream, Pasta})
85    0.001170  frozenset({Shaving Cream, Cleaning Spray})
...        ...                                         ...
3316  0.001070                   frozenset({Coffee, Rice})
3317  0.001240                   frozenset({Rice, Banana})
3318  0.001195            frozenset({Peanut Butter, Rice})
3319  0.001178        frozenset({Laundry Detergent, Rice})
3320  0.001199                    frozenset({Chips, Rice})

[3240 rows x 2 columns]